import React, { useState, useCallback, useEffect } from 'react';
import { 
  Server, Plus, Trash2, Edit2, Check, X, 
  ExternalLink, Key, Globe, Clock, Save, RefreshCw, SlidersHorizontal, Map as MapIcon,
  Package, Copy, FolderOpen, ChevronRight, File, Folder, HardDrive, Database,
  Shield, Plug, LifeBuoy
} from 'lucide-react';
import { Button, Card, Badge } from '../ui';
import {
  ACTIVE_SERVER_CHANGED_EVENT,
  SERVER_CONFIG_CHANGED_EVENT,
  getServers, 
  updateServer, 
  deleteServer, 
  getActiveServerId,
  getActiveServer,
  getServerContextKey,
  setActiveServerId 
} from '../../services/serverManager';
import api from '../../services/api';
import { clearAuthTokenForServer, copyAuthTokenToServer } from '../../services/auth';
import { normalizeApiUrl, resolveServerProfile } from '../../services/serverProfiles';
import type { ConfigBrowseResponse, RuntimeEnvValues, ServerConfig, SstModInfoResponse } from '../../types';
import { getMapPresetDefaults, MAP_PRESET_OPTIONS } from '../../maps/mapConfig';
import { AddServerSetup } from './AddServerSetup';

interface ServerSettingsProps {
  onServerChange?: () => void;
}

type EnvFieldType = 'text' | 'password' | 'number' | 'select' | 'toggle';
type PathBrowseMode = 'folder' | 'file';

interface EnvField {
  key: string;
  label: string;
  type?: EnvFieldType;
  description?: string;
  pathMode?: PathBrowseMode;
  options?: { value: string; label: string }[];
}

interface EnvGroup {
  id: string;
  title: string;
  description: string;
  icon: React.ReactNode;
  fields: EnvField[];
}

interface PathBrowserState {
  fieldKey: string;
  label: string;
  mode: PathBrowseMode;
  selectedPath: string;
  loading: boolean;
  error: string;
  data: ConfigBrowseResponse | null;
}

const ENV_GROUPS: EnvGroup[] = [
  {
    id: 'server',
    title: 'Server',
    description: 'API listener, host, and dashboard access settings.',
    icon: <Server size={16} />,
    fields: [
      { key: 'PORT', label: 'API Port', type: 'number' },
      { key: 'HOST', label: 'API Host' },
      { key: 'CORS_ORIGIN', label: 'CORS Origin' },
    ],
  },
  {
    id: 'storage',
    title: 'Storage',
    description: 'Choose the storage backend and the root SST runtime folder.',
    icon: <HardDrive size={16} />,
    fields: [
      {
        key: 'STORAGE_BACKEND',
        label: 'Storage Backend',
        type: 'select',
        options: [
          { value: 'local', label: 'Local' },
          { value: 'sftp', label: 'SFTP' },
          { value: 'ftp', label: 'FTP' },
        ],
      },
      { key: 'SST_PATH', label: 'SST Runtime Path', pathMode: 'folder', description: 'Folder generated by the @SST server mod inside the active DayZ profile.' },
      { key: 'SST_API_PROVIDER_CONFIG', label: 'Provider Config Path', pathMode: 'file' },
      { key: 'HOST_PROVIDER', label: 'Host Provider' },
    ],
  },
  {
    id: 'sftp',
    title: 'SFTP',
    description: 'Remote SFTP credentials for hosted servers.',
    icon: <Plug size={16} />,
    fields: [
      { key: 'SFTP_HOST', label: 'Host' },
      { key: 'SFTP_PORT', label: 'Port', type: 'number' },
      { key: 'SFTP_USER', label: 'Username' },
      { key: 'SFTP_PASSWORD', label: 'Password', type: 'password' },
      { key: 'SFTP_ROOT', label: 'Remote Root' },
    ],
  },
  {
    id: 'ftp',
    title: 'FTP',
    description: 'FTP or FTPS credentials for hosted servers.',
    icon: <Globe size={16} />,
    fields: [
      { key: 'FTP_HOST', label: 'Host' },
      { key: 'FTP_PORT', label: 'Port', type: 'number' },
      { key: 'FTP_USER', label: 'Username' },
      { key: 'FTP_PASSWORD', label: 'Password', type: 'password' },
      { key: 'FTP_SECURE', label: 'FTPS', type: 'toggle' },
      { key: 'FTP_ROOT', label: 'Remote Root' },
    ],
  },
  {
    id: 'data-paths',
    title: 'Data Paths',
    description: 'SST JSON data files and queues written by the server mod.',
    icon: <Database size={16} />,
    fields: [
      { key: 'INVENTORIES_PATH', label: 'Inventories Path', pathMode: 'folder' },
      { key: 'EVENTS_PATH', label: 'Item Events Path', pathMode: 'folder' },
      { key: 'LIFE_EVENTS_PATH', label: 'Life Events Path', pathMode: 'folder' },
      { key: 'TRADES_PATH', label: 'Trades Path', pathMode: 'folder' },
      { key: 'API_PATH', label: 'API Queue Path', pathMode: 'folder' },
      { key: 'ONLINE_PLAYERS_PATH', label: 'Online Players File', pathMode: 'file' },
      { key: 'ONLINE_PLAYERS_STALE_AFTER_MS', label: 'Online Stale Timeout (ms)', type: 'number' },
      { key: 'AI_POSITIONS_PATH', label: 'AI Positions File', pathMode: 'file' },
      { key: 'AI_POSITIONS_STALE_AFTER_MS', label: 'AI Stale Timeout (ms)', type: 'number' },
    ],
  },
  {
    id: 'mission-expansion',
    title: 'Mission & Expansion',
    description: 'Mission files and DayZ Expansion configuration folders.',
    icon: <FolderOpen size={16} />,
    fields: [
      { key: 'PROFILES_PATH', label: 'Profiles Path', pathMode: 'folder', description: 'Active DayZ -profiles folder. Expansion folders are auto-detected from ExpansionMod inside this folder.' },
      { key: 'MISSION_PATH', label: 'Mission Files Path', pathMode: 'folder' },
      { key: 'TYPES_PATH', label: 'Main Types.xml Override', pathMode: 'file' },
      { key: 'EXPANSION_ENABLED', label: 'DayZ Expansion', type: 'toggle' },
    ],
  },
  {
    id: 'map',
    title: 'Map',
    description: 'Live map preset, image, world size, and axis conversion.',
    icon: <MapIcon size={16} />,
    fields: [
      { key: 'MAP_PRESET', label: 'Map Preset', type: 'select', options: MAP_PRESET_OPTIONS },
      { key: 'MAP_LABEL', label: 'Custom Map Label' },
      { key: 'MAP_IMAGE_URL', label: 'Map Image URL or Public Path' },
      { key: 'MAP_WORLD_SIZE_X', label: 'World Size X', type: 'number' },
      { key: 'MAP_WORLD_SIZE_Z', label: 'World Size Z', type: 'number' },
      { key: 'MAP_INVERT_X', label: 'Invert X Axis', type: 'toggle' },
      { key: 'MAP_INVERT_Z', label: 'Invert Z Axis', type: 'toggle' },
    ],
  },
  {
    id: 'logs-tracking',
    title: 'Logs & Tracking',
    description: 'Profiles folder, local databases, position tracking, and archive timing.',
    icon: <Clock size={16} />,
    fields: [
      { key: 'AUTH_DB_PATH', label: 'Auth Database Path', pathMode: 'file' },
      { key: 'DATABASE_PATH', label: 'Position Database Path', pathMode: 'file' },
      { key: 'POSITION_TRACKING_INTERVAL', label: 'Position Interval (ms)', type: 'number' },
      { key: 'ARCHIVE_HOUR', label: 'Archive Hour', type: 'number' },
      { key: 'ARCHIVE_MINUTE', label: 'Archive Minute', type: 'number' },
      { key: 'ARCHIVE_DB_PATH', label: 'Archive Database Path', pathMode: 'file' },
    ],
  },
  {
    id: 'discord-support',
    title: 'Discord Support',
    description: 'Optional ticket bot setup. Users must provide a Steam64 ID when opening a ticket.',
    icon: <LifeBuoy size={16} />,
    fields: [
      { key: 'DISCORD_ENABLED', label: 'Discord Ticket Bot', type: 'toggle' },
      { key: 'DISCORD_BOT_TOKEN', label: 'Bot Token', type: 'password', description: 'Saved to this server profile .env. Never commit this value.' },
      { key: 'DISCORD_CLIENT_ID', label: 'Application Client ID', description: 'Application ID from the Discord Developer Portal.' },
      { key: 'DISCORD_GUILD_ID', label: 'Discord Server ID', description: 'Right-click your Discord server and copy ID.' },
      { key: 'DISCORD_TICKET_CATEGORY_ID', label: 'Ticket Category ID', description: 'Parent category where private ticket channels are created.' },
      { key: 'DISCORD_TICKET_PANEL_CHANNEL_ID', label: 'Raise Ticket Channel ID', description: 'Public channel where SST publishes the dropdown ticket panel.' },
      { key: 'DISCORD_STAFF_ROLE_ID', label: 'Staff Role ID', description: 'Staff role that can see private ticket channels.' },
      { key: 'DISCORD_LOG_CHANNEL_ID', label: 'Log Channel ID', description: 'Optional channel for future ticket audit posts.' },
      { key: 'DISCORD_COMMAND_NAME', label: 'Slash Command Name' },
      { key: 'DISCORD_TICKET_CHANNEL_PREFIX', label: 'Ticket Channel Prefix' },
      { key: 'DISCORD_TICKET_DB_PATH', label: 'Ticket Database Path', pathMode: 'file' },
    ],
  },
  {
    id: 'security-updates',
    title: 'Security & Updates',
    description: 'API keys, bootstrap admin, and update controls.',
    icon: <Shield size={16} />,
    fields: [
      { key: 'API_KEY', label: 'API Key', type: 'password' },
      { key: 'JWT_SECRET', label: 'JWT Secret', type: 'password' },
      { key: 'SST_AUTO_CREATE_ADMIN', label: 'Auto Create Admin', type: 'toggle' },
      { key: 'INITIAL_ADMIN_USERNAME', label: 'Initial Admin Username' },
      { key: 'INITIAL_ADMIN_PASSWORD', label: 'Initial Admin Password', type: 'password' },
      { key: 'SST_DISABLE_UPDATE_CHECK', label: 'Disable Update Checks', type: 'toggle' },
      { key: 'SST_UPDATE_REPO', label: 'Update Repo' },
      { key: 'SST_ALLOW_REMOTE_UPDATE', label: 'Allow Remote Updates', type: 'toggle' },
    ],
  },
];

const isToggleOn = (value: string | undefined) => value === '1' || value === 'true';
const EXPANSION_CHILD_PATH_KEYS = [
  'EXPANSION_TRADERS_PATH',
  'EXPANSION_MARKET_PATH',
  'EXPANSION_ATM_PATH',
  'EXPANSION_AI_PATH',
  'EXPANSION_QUESTS_PATH',
] as const;
const AUTO_DERIVED_ENV_KEYS = new Set<string>(EXPANSION_CHILD_PATH_KEYS);

const normalizeUiPath = (value: string | undefined) => String(value || '').trim().replace(/\\/g, '/').replace(/\/+$/, '');

const joinUiPath = (base: string, ...parts: string[]) => {
  const cleanBase = normalizeUiPath(base);
  const cleanParts = parts.map(part => part.replace(/^\/+|\/+$/g, '')).filter(Boolean);
  return cleanBase ? [cleanBase, ...cleanParts].join('/') : cleanParts.join('/');
};

const sameApiUrl = (left?: string | null, right?: string | null) => {
  return normalizeApiUrl(left).toLowerCase() === normalizeApiUrl(right).toLowerCase();
};

const DISCORD_ID_KEYS = new Set([
  'DISCORD_CLIENT_ID',
  'DISCORD_GUILD_ID',
  'DISCORD_TICKET_CATEGORY_ID',
  'DISCORD_TICKET_PANEL_CHANNEL_ID',
  'DISCORD_STAFF_ROLE_ID',
  'DISCORD_LOG_CHANNEL_ID',
]);

const DISCORD_REQUIRED_KEYS = [
  'DISCORD_ENABLED',
  'DISCORD_BOT_TOKEN',
  'DISCORD_CLIENT_ID',
  'DISCORD_GUILD_ID',
  'DISCORD_TICKET_CATEGORY_ID',
  'DISCORD_TICKET_PANEL_CHANNEL_ID',
];

const extractDiscordId = (value: string) => {
  const matches = String(value || '').match(/\d{16,22}/g);
  return matches?.[matches.length - 1] || value;
};

const getApiErrorMessage = (err: unknown, fallback: string) => {
  const apiError = err as { response?: { data?: { error?: string; details?: string } }; message?: string };
  return apiError.response?.data?.details || apiError.response?.data?.error || apiError.message || fallback;
};

const fillMissingEnvValues = (
  values: RuntimeEnvValues,
  suggestions: RuntimeEnvValues = {}
) => {
  const nextValues = { ...values };
  let filledCount = 0;

  for (const [key, suggestedValue] of Object.entries(suggestions)) {
    if (AUTO_DERIVED_ENV_KEYS.has(key)) continue;

    const currentValue = String(nextValues[key] ?? '').trim();
    const normalizedSuggestion = String(suggestedValue ?? '').trim();

    if (!currentValue && normalizedSuggestion) {
      nextValues[key] = normalizedSuggestion;
      filledCount += 1;
    }
  }

  return { values: nextValues, filledCount };
};

export const ServerSettings: React.FC<ServerSettingsProps> = ({ onServerChange }) => {
  const [servers, setServers] = useState<ServerConfig[]>([]);
  const [activeId, setActiveId] = useState<string | null>(null);
  const [activeContextKey, setActiveContextKey] = useState(() => getServerContextKey());
  const [editingId, setEditingId] = useState<string | null>(null);
  const [showAddForm, setShowAddForm] = useState(false);
  
  // Form state
  const [formName, setFormName] = useState('');
  const [formUrl, setFormUrl] = useState('http://localhost:3001');
  const [formProfile, setFormProfile] = useState('');
  const [formKey, setFormKey] = useState('');
  const [formError, setFormError] = useState('');
  
  // Testing state
  const [testingId, setTestingId] = useState<string | null>(null);
  const [testResults, setTestResults] = useState<Record<string, 'success' | 'error' | null>>({});

  // Active API .env state
  const [envValues, setEnvValues] = useState<RuntimeEnvValues>({});
  const [envSuggestions, setEnvSuggestions] = useState<RuntimeEnvValues>({});
  const [envPath, setEnvPath] = useState('');
  const [configLoading, setConfigLoading] = useState(false);
  const [configSaving, setConfigSaving] = useState(false);
  const [configError, setConfigError] = useState('');
  const [configMessage, setConfigMessage] = useState('');
  const [activeEnvGroupId, setActiveEnvGroupId] = useState('servers');
  const [pathBrowser, setPathBrowser] = useState<PathBrowserState | null>(null);
  const [modInfo, setModInfo] = useState<SstModInfoResponse | null>(null);
  const [modDestination, setModDestination] = useState('');
  const [modCopying, setModCopying] = useState(false);
  const [modMessage, setModMessage] = useState('');
  const [modError, setModError] = useState('');

  // Load servers
  const loadServers = useCallback(() => {
    setServers(getServers());
    setActiveId(getActiveServerId());
    setActiveContextKey(getServerContextKey(getActiveServer()));
  }, []);

  const loadRuntimeConfig = useCallback(async () => {
    if (!getActiveServerId()) {
      setEnvValues({});
      setEnvSuggestions({});
      setEnvPath('');
      setModInfo(null);
      return;
    }

    setConfigLoading(true);
    setConfigError('');
    setConfigMessage('');

    try {
      api.loadActiveServer();
      const config = await api.getRuntimeConfig();
      const suggestions = config.suggestions || {};
      const filled = fillMissingEnvValues(config.env || {}, suggestions);
      setEnvValues(filled.values);
      setEnvSuggestions(suggestions);
      setEnvPath(config.envPath || '');
      setModInfo(config.mod || null);
      if (filled.filledCount > 0) {
        setConfigMessage(`Auto-filled ${filled.filledCount} unset settings from known server paths. Review them, then Save .env to persist.`);
      }
    } catch (err) {
      setConfigError(getApiErrorMessage(err, 'Failed to load server settings'));
    } finally {
      setConfigLoading(false);
    }
  }, []);

  useEffect(() => {
    loadServers();
  }, [loadServers]);

  useEffect(() => {
    loadRuntimeConfig();
  }, [activeContextKey, loadRuntimeConfig]);

  useEffect(() => {
    window.addEventListener(SERVER_CONFIG_CHANGED_EVENT, loadServers);
    window.addEventListener(ACTIVE_SERVER_CHANGED_EVENT, loadServers);

    return () => {
      window.removeEventListener(SERVER_CONFIG_CHANGED_EVENT, loadServers);
      window.removeEventListener(ACTIVE_SERVER_CHANGED_EVENT, loadServers);
    };
  }, [loadServers]);

  // Test a server connection
  const testConnection = async (server: ServerConfig) => {
    setTestingId(server.id);
    setTestResults(prev => ({ ...prev, [server.id]: null }));
    
    try {
      const resolved = await resolveServerProfile(server, { createIfMissing: true });
      if (resolved.changed) {
        loadServers();
        if (server.id === activeId) {
          api.configure(resolved.server.apiUrl, resolved.server.apiKey, resolved.server.apiProfile);
        }
      }
      setTestResults(prev => ({ ...prev, [server.id]: 'success' }));
    } catch {
      setTestResults(prev => ({ ...prev, [server.id]: 'error' }));
    } finally {
      setTestingId(null);
    }
  };

  // Update existing server
  const handleUpdateServer = (id: string) => {
    if (!formName.trim() || !formUrl.trim() || !formKey.trim()) {
      setFormError('All fields are required');
      return;
    }

    const currentServer = servers.find(server => server.id === id);
    const nextApiUrl = formUrl.trim().replace(/\/$/, '');
    const nextApiProfile = formProfile.trim();
    const apiUrlChanged = Boolean(
      currentServer &&
      (currentServer.apiUrl !== nextApiUrl || (currentServer.apiProfile || '') !== nextApiProfile)
    );

    updateServer(id, {
      name: formName.trim(),
      apiUrl: nextApiUrl,
      apiProfile: nextApiProfile,
      apiKey: formKey.trim(),
    });

    if (apiUrlChanged) {
      clearAuthTokenForServer(id);
    }

    setEditingId(null);
    setFormError('');
    loadServers();
    
    // If we updated the active server, reload its config
    if (id === activeId) {
      api.loadActiveServer();
      onServerChange?.();
    }
  };

  // Delete a server
  const handleDeleteServer = (id: string) => {
    if (confirm('Are you sure you want to delete this server?')) {
      deleteServer(id);
      loadServers();
      
      if (id === activeId) {
        api.loadActiveServer();
      }
    }
  };

  // Switch active server
  const handleSwitchServer = async (id: string) => {
    const currentServer = servers.find(server => server.id === activeId);
    const targetServer = servers.find(server => server.id === id);
    if (!targetServer) return;

    setConfigError('');

    try {
      const resolved = await resolveServerProfile(targetServer, { createIfMissing: true });
      if (currentServer && sameApiUrl(currentServer.apiUrl, resolved.server.apiUrl)) {
        copyAuthTokenToServer(resolved.server.id);
      }

      api.configure(resolved.server.apiUrl, resolved.server.apiKey, resolved.server.apiProfile);
      setActiveServerId(resolved.server.id);
      setActiveId(resolved.server.id);
      setActiveContextKey(getServerContextKey(resolved.server));
      loadServers();
    } catch (err) {
      setConfigError(getApiErrorMessage(err, 'Could not switch SST server profile'));
    }
  };

  // Start editing a server
  const startEditing = (server: ServerConfig) => {
    setEditingId(server.id);
    setFormName(server.name);
    setFormUrl(server.apiUrl);
    setFormProfile(server.apiProfile || '');
    setFormKey(server.apiKey);
    setFormError('');
  };

  // Cancel editing
  const cancelEditing = () => {
    setEditingId(null);
    setFormName('');
    setFormUrl('http://localhost:3001');
    setFormProfile('');
    setFormKey('');
    setFormError('');
  };

  const updateEnvValue = (key: string, value: string) => {
    const nextValue = DISCORD_ID_KEYS.has(key) ? extractDiscordId(value.trim()) : value;
    setEnvValues(prev => {
      const nextValues = { ...prev, [key]: nextValue };

      if (key === 'PROFILES_PATH') {
        for (const expansionKey of EXPANSION_CHILD_PATH_KEYS) {
          nextValues[expansionKey] = '';
        }
      }

      return nextValues;
    });
    if (key === 'PROFILES_PATH') {
      setConfigMessage('Expansion folders will be auto-detected from the selected Profiles Path after saving.');
    } else if (DISCORD_ID_KEYS.has(key) && nextValue !== value.trim()) {
      setConfigMessage('Extracted the numeric Discord ID from the pasted link.');
    } else {
      setConfigMessage('');
    }
    setConfigError('');
  };

  const updateMapPresetEnvValue = (value: string) => {
    if (!value) {
      updateEnvValue('MAP_PRESET', '');
      return;
    }

    const defaults = getMapPresetDefaults(value);
    setEnvValues(prev => ({
      ...prev,
      MAP_PRESET: defaults.id,
      MAP_LABEL: defaults.id === 'custom' ? prev.MAP_LABEL || '' : '',
      MAP_IMAGE_URL: defaults.imageUrl,
      MAP_WORLD_SIZE_X: String(defaults.worldSizeX),
      MAP_WORLD_SIZE_Z: String(defaults.worldSizeZ),
      MAP_INVERT_X: '0',
      MAP_INVERT_Z: '0',
    }));
    setConfigMessage(`${defaults.label} map defaults applied. Review them, then Save .env to persist.`);
    setConfigError('');
  };

  const autoFillRuntimeConfig = () => {
    const filled = fillMissingEnvValues(envValues, envSuggestions);
    setEnvValues(filled.values);
    setConfigError('');
    setConfigMessage(
      filled.filledCount > 0
        ? `Auto-filled ${filled.filledCount} blank settings. Review them, then Save .env to persist.`
        : 'No blank settings needed auto-fill.'
    );
  };

  const saveRuntimeConfig = async () => {
    setConfigSaving(true);
    setConfigError('');
    setConfigMessage('');

    try {
      const result = await api.updateRuntimeConfig(envValues);
      const activeServer = servers.find(server => server.id === activeId);
      const mapDefaults = getMapPresetDefaults(envValues.MAP_PRESET);

      if (activeServer && envValues.API_KEY && envValues.API_KEY !== activeServer.apiKey) {
        for (const server of servers) {
          if (server.apiUrl === activeServer.apiUrl) {
            updateServer(server.id, { apiKey: envValues.API_KEY });
          }
        }
        api.configure(activeServer.apiUrl, envValues.API_KEY, activeServer.apiProfile);
      }

      if (activeServer && envValues.MAP_PRESET) {
        updateServer(activeServer.id, {
          mapPreset: mapDefaults.id,
          mapLabel: envValues.MAP_LABEL || mapDefaults.label,
          mapImageUrl: envValues.MAP_IMAGE_URL || mapDefaults.imageUrl,
          mapWorldSizeX: Number(envValues.MAP_WORLD_SIZE_X) || mapDefaults.worldSizeX,
          mapWorldSizeZ: Number(envValues.MAP_WORLD_SIZE_Z) || mapDefaults.worldSizeZ,
          mapInvertX: isToggleOn(envValues.MAP_INVERT_X),
          mapInvertZ: isToggleOn(envValues.MAP_INVERT_Z),
        });
      }

      loadServers();
      setConfigMessage(result.message || 'Settings saved.');
    } catch (err) {
      setConfigError(getApiErrorMessage(err, 'Failed to save server settings'));
    } finally {
      setConfigSaving(false);
    }
  };

  const copyModPath = async () => {
    if (!modInfo?.path) return;

    try {
      await navigator.clipboard.writeText(modInfo.path);
      setModError('');
      setModMessage('@SST path copied.');
    } catch {
      setModError('Could not copy the @SST path.');
      setModMessage('');
    }
  };

  const copyModToDestination = async () => {
    const destination = modDestination.trim();
    if (!destination) {
      setModError('Enter a DayZ server folder first.');
      setModMessage('');
      return;
    }

    setModCopying(true);
    setModError('');
    setModMessage('');

    try {
      const result = await api.copySstMod(destination);
      setModMessage(result.message || `Copied @SST to ${result.destinationPath}`);
      const refreshed = await api.getSstModInfo();
      setModInfo(refreshed);
    } catch (err) {
      const apiError = err as { response?: { data?: { error?: string; details?: string } } };
      setModError(apiError.response?.data?.details || apiError.response?.data?.error || 'Failed to copy @SST.');
    } finally {
      setModCopying(false);
    }
  };

  const openPathBrowserTarget = async (
    fieldKey: string,
    label: string,
    mode: PathBrowseMode,
    initialPath: string
  ) => {
    const startingPath = initialPath.trim();
    setPathBrowser({
      fieldKey,
      label,
      mode,
      selectedPath: startingPath,
      loading: true,
      error: '',
      data: null,
    });

    try {
      const data = await api.browseConfigPath(startingPath, mode);
      setPathBrowser(prev => prev && prev.fieldKey === fieldKey
        ? {
            ...prev,
            loading: false,
            data,
            selectedPath: startingPath || data.currentPath,
          }
        : prev
      );
    } catch (err) {
      const apiError = err as { response?: { data?: { error?: string; details?: string } } };
      setPathBrowser(prev => prev && prev.fieldKey === fieldKey
        ? {
            ...prev,
            loading: false,
            error: apiError.response?.data?.details || apiError.response?.data?.error || 'Failed to browse paths.',
          }
        : prev
      );
    }
  };

  const openPathBrowser = (field: EnvField) => {
    if (!field.pathMode) return;
    openPathBrowserTarget(
      field.key,
      field.label,
      field.pathMode,
      envValues[field.key] || envSuggestions[field.key] || ''
    );
  };

  const browseToPath = async (nextPath: string) => {
    if (!pathBrowser) return;

    setPathBrowser(prev => prev ? { ...prev, loading: true, error: '' } : prev);

    try {
      const data = await api.browseConfigPath(nextPath, pathBrowser.mode);
      setPathBrowser(prev => prev
        ? {
            ...prev,
            loading: false,
            data,
            selectedPath: pathBrowser.mode === 'folder' ? data.currentPath : prev.selectedPath,
          }
        : prev
      );
    } catch (err) {
      const apiError = err as { response?: { data?: { error?: string; details?: string } } };
      setPathBrowser(prev => prev
        ? {
            ...prev,
            loading: false,
            error: apiError.response?.data?.details || apiError.response?.data?.error || 'Failed to browse paths.',
          }
        : prev
      );
    }
  };

  const applyBrowsedPath = () => {
    if (!pathBrowser) return;
    const nextPath = pathBrowser.selectedPath || pathBrowser.data?.currentPath || '';
    if (!nextPath) return;

    if (pathBrowser.fieldKey === '__modDestination') {
      setModDestination(nextPath);
      setModError('');
      setModMessage('');
    } else {
      updateEnvValue(pathBrowser.fieldKey, nextPath);
    }

    setPathBrowser(null);
  };

  const resetExpansionPathsToAuto = () => {
    setEnvValues(prev => {
      const nextValues = { ...prev };
      for (const key of EXPANSION_CHILD_PATH_KEYS) {
        nextValues[key] = '';
      }
      return nextValues;
    });
    setConfigError('');
    setConfigMessage('Expansion folder overrides cleared. Save .env and restart to use Profiles Path auto-detection.');
  };

  const renderExpansionAutoPaths = () => {
    const profilesPath = normalizeUiPath(envValues.PROFILES_PATH || envSuggestions.PROFILES_PATH);
    const expansionBase = profilesPath ? joinUiPath(profilesPath, 'ExpansionMod') : '';
    const explicitOverrides = EXPANSION_CHILD_PATH_KEYS
      .map(key => ({ key, value: normalizeUiPath(envValues[key]) }))
      .filter(item => item.value);
    const rows = [
      { key: 'EXPANSION_TRADERS_PATH', label: 'Traders', path: expansionBase ? joinUiPath(expansionBase, 'Traders') : '' },
      { key: 'EXPANSION_MARKET_PATH', label: 'Market', path: expansionBase ? joinUiPath(expansionBase, 'Market') : '' },
      { key: 'EXPANSION_ATM_PATH', label: 'ATM', path: expansionBase ? joinUiPath(expansionBase, 'ATM') : '' },
      { key: 'EXPANSION_AI_PATH', label: 'AI', path: expansionBase ? joinUiPath(expansionBase, 'AI') : '' },
      { key: 'EXPANSION_QUESTS_PATH', label: 'Quests', path: expansionBase ? joinUiPath(expansionBase, 'Quests') : '' },
    ];

    return (
      <div className="lg:col-span-2 rounded-xl border border-primary-200 bg-primary-50 p-4">
        <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
          <div>
            <div className="flex items-center gap-2">
              <FolderOpen size={16} className="text-primary-700" />
              <h4 className="text-sm font-semibold text-primary-950">Expansion folders auto-detect from Profiles Path</h4>
              <Badge variant={explicitOverrides.length > 0 ? 'warning' : 'success'}>
                {explicitOverrides.length > 0 ? 'Stored overrides' : 'Auto'}
              </Badge>
            </div>
            <p className="mt-1 text-sm text-primary-800">
              Point Profiles Path at the active DayZ profile folder. SST will use the `ExpansionMod` folder inside it for Expansion tools.
            </p>
          </div>
          <Button
            type="button"
            size="sm"
            variant="secondary"
            onClick={resetExpansionPathsToAuto}
            disabled={explicitOverrides.length === 0}
          >
            Use Profiles Path
          </Button>
        </div>

        {profilesPath ? (
          <div className="mt-4 grid grid-cols-1 gap-2 md:grid-cols-2">
            {rows.map(row => {
              const override = explicitOverrides.find(item => item.key === row.key);
              return (
                <div key={row.key} className="rounded-lg border border-primary-100 bg-white p-3">
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-xs font-semibold uppercase tracking-wide text-surface-500">{row.label}</span>
                    <span className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${
                      override ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700'
                    }`}>
                      {override ? 'Stored' : 'Auto'}
                    </span>
                  </div>
                  <code className="mt-2 block break-all text-xs text-surface-700">
                    {override?.value || row.path}
                  </code>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="mt-4 rounded-lg border border-dashed border-primary-200 bg-white/60 p-3 text-sm text-primary-800">
            Choose a Profiles Path to enable automatic Expansion folder detection.
          </div>
        )}
      </div>
    );
  };

  const discordField = (key: string) => ENV_GROUPS
    .find(group => group.id === 'discord-support')
    ?.fields.find(field => field.key === key);

  const renderDiscordTextField = (key: string, options: { required?: boolean; secret?: boolean; placeholder?: string } = {}) => {
    const field = discordField(key);
    if (!field) return null;

    const value = envValues[key] ?? '';
    const isMissing = options.required && !String(value).trim();

    return (
      <label key={key} className={`block rounded-xl border bg-white p-4 ${
        isMissing ? 'border-amber-200' : 'border-surface-200'
      }`}>
        <div className="flex items-start justify-between gap-3">
          <span>
            <span className="block text-sm font-semibold text-surface-800">{field.label}</span>
            {field.description && <span className="mt-1 block text-xs leading-relaxed text-surface-500">{field.description}</span>}
          </span>
          {options.required && (
            <Badge variant={isMissing ? 'warning' : 'success'}>
              {isMissing ? 'Needed' : 'Set'}
            </Badge>
          )}
        </div>

        <div className="mt-3 flex gap-2">
          <input
            type={options.secret ? 'password' : 'text'}
            value={value}
            onChange={(event) => updateEnvValue(key, event.target.value)}
            placeholder={options.placeholder || (DISCORD_ID_KEYS.has(key) ? 'Paste ID or Discord link' : '')}
            className="w-full rounded-lg border border-surface-300 bg-white px-3 py-2 text-sm text-surface-800 outline-none transition-colors focus:border-primary-500 focus:ring-2 focus:ring-primary-100"
          />
          {field.pathMode && (
            <Button
              type="button"
              size="sm"
              variant="secondary"
              onClick={() => openPathBrowser(field)}
              icon={field.pathMode === 'file' ? <File size={14} /> : <FolderOpen size={14} />}
              className="shrink-0"
            >
              Browse
            </Button>
          )}
        </div>
        <code className="mt-2 block text-[11px] text-surface-400">{key}</code>
      </label>
    );
  };

  const renderDiscordSupportPanel = () => {
    const requiredSetCount = DISCORD_REQUIRED_KEYS
      .filter(key => key === 'DISCORD_ENABLED' ? isToggleOn(envValues[key]) : String(envValues[key] ?? '').trim())
      .length;
    const isEnabled = isToggleOn(envValues.DISCORD_ENABLED);

    return (
      <div className="space-y-5 lg:col-span-2">
        <div className="rounded-2xl border border-surface-200 bg-surface-50 p-4 sm:p-5">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
            <div>
              <div className="flex items-center gap-2 text-surface-500">
                <LifeBuoy size={17} />
                <span className="text-xs font-semibold uppercase tracking-wide">Ticket bot setup</span>
              </div>
              <h4 className="mt-2 text-lg font-semibold text-surface-900">Create private Discord ticket channels from SST</h4>
              <p className="mt-1 max-w-3xl text-sm leading-relaxed text-surface-600">
                Fill the required items below. Users will click the public panel in your raise-ticket channel, enter their Steam64 ID, and SST will create a private ticket channel under your ticket category.
              </p>
            </div>
            <div className="rounded-xl border border-surface-200 bg-white px-4 py-3">
              <div className="text-xs font-medium text-surface-500">Required setup</div>
              <div className="mt-1 text-2xl font-semibold text-surface-900">{requiredSetCount}/{DISCORD_REQUIRED_KEYS.length}</div>
            </div>
          </div>

          <div className="mt-4 grid gap-3 md:grid-cols-3">
            <div className="rounded-xl border border-surface-200 bg-white p-3">
              <div className="text-xs font-semibold uppercase tracking-wide text-surface-500">1. Bot application</div>
              <div className="mt-1 text-sm text-surface-700">Token and Application ID from the Discord Developer Portal.</div>
            </div>
            <div className="rounded-xl border border-surface-200 bg-white p-3">
              <div className="text-xs font-semibold uppercase tracking-wide text-surface-500">2. Server IDs</div>
              <div className="mt-1 text-sm text-surface-700">Server, category, and raise-ticket channel IDs. Pasted links are okay.</div>
            </div>
            <div className="rounded-xl border border-surface-200 bg-white p-3">
              <div className="text-xs font-semibold uppercase tracking-wide text-surface-500">3. Publish panel</div>
              <div className="mt-1 text-sm text-surface-700">After saving and restart, use Support Tickets &gt; Publish Panel.</div>
            </div>
          </div>
        </div>

        <label className="flex items-center justify-between gap-4 rounded-xl border border-surface-200 bg-white p-4">
          <span>
            <span className="block text-sm font-semibold text-surface-800">Enable Discord ticket bot</span>
            <span className="mt-1 block text-xs text-surface-500">Leave this off until token, server ID, category, and raise-ticket channel are filled.</span>
            <code className="mt-1 block text-[11px] text-surface-400">DISCORD_ENABLED</code>
          </span>
          <div className="flex items-center gap-3">
            <Badge variant={isEnabled ? 'success' : 'default'}>{isEnabled ? 'On' : 'Off'}</Badge>
            <input
              type="checkbox"
              checked={isEnabled}
              onChange={(event) => updateEnvValue('DISCORD_ENABLED', event.target.checked ? '1' : '0')}
              className="h-4 w-4 rounded border-surface-300"
            />
          </div>
        </label>

        <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
          {renderDiscordTextField('DISCORD_BOT_TOKEN', { required: true, secret: true, placeholder: 'Paste bot token' })}
          {renderDiscordTextField('DISCORD_CLIENT_ID', { required: true })}
          {renderDiscordTextField('DISCORD_GUILD_ID', { required: true, placeholder: 'Discord server ID' })}
          {renderDiscordTextField('DISCORD_TICKET_CATEGORY_ID', { required: true, placeholder: 'Parent category ID for ticket-0001 channels' })}
          {renderDiscordTextField('DISCORD_TICKET_PANEL_CHANNEL_ID', { required: true, placeholder: '#raise-ticket channel ID' })}
          {renderDiscordTextField('DISCORD_STAFF_ROLE_ID', { placeholder: 'Staff role ID' })}
        </div>

        <div className="rounded-2xl border border-surface-200 bg-white p-4 sm:p-5">
          <div className="flex items-center justify-between gap-3">
            <div>
              <h4 className="text-sm font-semibold text-surface-900">Advanced defaults</h4>
              <p className="mt-1 text-sm text-surface-500">These can usually stay as-is.</p>
            </div>
            <Badge variant="default">Optional</Badge>
          </div>
          <div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-2">
            {renderDiscordTextField('DISCORD_COMMAND_NAME', { placeholder: 'ticket' })}
            {renderDiscordTextField('DISCORD_TICKET_CHANNEL_PREFIX', { placeholder: 'ticket' })}
            {renderDiscordTextField('DISCORD_LOG_CHANNEL_ID', { placeholder: 'Optional log channel ID' })}
            {renderDiscordTextField('DISCORD_TICKET_DB_PATH', { placeholder: 'Leave blank for SST default' })}
          </div>
        </div>
      </div>
    );
  };

  const renderEnvField = (field: EnvField) => {
    const value = envValues[field.key] ?? '';
    const suggestedValue = envSuggestions[field.key];
    const inputClassName = 'w-full rounded-lg border border-surface-300 bg-white px-3 py-2 text-sm text-surface-800 outline-none transition-colors focus:border-primary-500 focus:ring-2 focus:ring-primary-100';

    if (field.type === 'toggle') {
      return (
        <label key={field.key} className="flex items-center justify-between gap-4 rounded-xl border border-surface-200 bg-white p-4">
          <span>
            <span className="block text-sm font-medium text-surface-700">{field.label}</span>
            {field.description && <span className="mt-1 block text-xs text-surface-500">{field.description}</span>}
            <code className="mt-1 block text-[11px] text-surface-400">{field.key}</code>
          </span>
          <input
            type="checkbox"
            checked={isToggleOn(value)}
            onChange={(e) => updateEnvValue(field.key, e.target.checked ? '1' : '0')}
            className="h-4 w-4 rounded border-surface-300"
          />
        </label>
      );
    }

    if (field.type === 'select') {
      return (
        <label key={field.key} className="block rounded-xl border border-surface-200 bg-white p-4">
          <span className="block text-sm font-medium text-surface-700">{field.label}</span>
          {field.description && <span className="mt-1 block text-xs text-surface-500">{field.description}</span>}
          <select
            value={value}
            onChange={(e) => {
              if (field.key === 'MAP_PRESET') {
                updateMapPresetEnvValue(e.target.value);
                return;
              }
              updateEnvValue(field.key, e.target.value);
            }}
            className={`${inputClassName} mt-2`}
          >
            <option value="">Default</option>
            {field.options?.map(option => (
              <option key={option.value} value={option.value}>{option.label}</option>
            ))}
          </select>
          <code className="mt-2 block text-[11px] text-surface-400">{field.key}</code>
        </label>
      );
    }

    return (
      <label key={field.key} className="block rounded-xl border border-surface-200 bg-white p-4">
        <span className="block text-sm font-medium text-surface-700">{field.label}</span>
        {field.description && <span className="mt-1 block text-xs text-surface-500">{field.description}</span>}
        <div className="mt-2 flex gap-2">
          <input
            type={field.type || 'text'}
            value={value}
            onChange={(e) => updateEnvValue(field.key, e.target.value)}
            className={inputClassName}
          />
          {field.pathMode && (
            <Button
              type="button"
              size="sm"
              variant="secondary"
              onClick={() => openPathBrowser(field)}
              icon={field.pathMode === 'file' ? <File size={14} /> : <FolderOpen size={14} />}
              className="shrink-0"
            >
              Browse
            </Button>
          )}
        </div>
        <span className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-1">
          <code className="text-[11px] text-surface-400">{field.key}</code>
          {!value && suggestedValue && (
            <span className="truncate text-[11px] text-surface-400">
              Suggested: {suggestedValue}
            </span>
          )}
        </span>
      </label>
    );
  };

  const renderPathBrowserModal = () => {
    if (!pathBrowser) return null;

    const currentPath = pathBrowser.data?.currentPath || '';
    const selectedPath = pathBrowser.selectedPath || currentPath;

    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
        <div className="flex max-h-[86vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl bg-white shadow-xl">
          <div className="border-b border-surface-200 p-4">
            <div className="flex items-start justify-between gap-4">
              <div>
                <h3 className="text-lg font-semibold text-surface-900">
                  Browse {pathBrowser.mode === 'file' ? 'File' : 'Folder'}
                </h3>
                <p className="mt-1 text-sm text-surface-500">{pathBrowser.label}</p>
              </div>
              <button
                type="button"
                onClick={() => setPathBrowser(null)}
                className="rounded-lg p-2 text-surface-500 hover:bg-surface-100 hover:text-surface-800"
              >
                <X size={18} />
              </button>
            </div>

            <div className="mt-3 rounded-lg bg-surface-50 px-3 py-2 text-xs text-surface-600">
              <span className="font-medium text-surface-700">Selected:</span>{' '}
              <code className="break-all">{selectedPath || 'Choose a path'}</code>
            </div>
          </div>

          <div className="grid min-h-0 flex-1 grid-cols-1 md:grid-cols-[210px_1fr]">
            <aside className="border-b border-surface-200 bg-surface-50 p-3 md:border-b-0 md:border-r">
              <div className="mb-2 text-xs font-semibold uppercase tracking-wide text-surface-500">Roots</div>
              <div className="space-y-1">
                {pathBrowser.data?.roots.map(root => (
                  <button
                    key={root.path}
                    type="button"
                    onClick={() => browseToPath(root.path)}
                    className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-sm text-surface-700 hover:bg-white"
                  >
                    <HardDrive size={15} />
                    <span className="truncate">{root.name}</span>
                  </button>
                ))}
              </div>
            </aside>

            <div className="min-h-0 p-3">
              <div className="mb-3 flex flex-col gap-2 sm:flex-row sm:items-center">
                <div className="min-w-0 flex-1 rounded-lg border border-surface-200 bg-surface-50 px-3 py-2 text-xs">
                  <code className="break-all text-surface-600">{currentPath || 'Computer'}</code>
                </div>
                <div className="flex gap-2">
                  {pathBrowser.data?.parentPath && (
                    <Button
                      type="button"
                      size="sm"
                      variant="secondary"
                      onClick={() => browseToPath(pathBrowser.data?.parentPath || '')}
                    >
                      Up
                    </Button>
                  )}
                  {pathBrowser.mode === 'folder' && currentPath && (
                    <Button
                      type="button"
                      size="sm"
                      variant="secondary"
                      onClick={() => setPathBrowser(prev => prev ? { ...prev, selectedPath: currentPath } : prev)}
                    >
                      Select Current
                    </Button>
                  )}
                </div>
              </div>

              {pathBrowser.error && (
                <div className="mb-3 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">
                  {pathBrowser.error}
                </div>
              )}

              <div className="min-h-0 overflow-y-auto rounded-lg border border-surface-200">
                {pathBrowser.loading ? (
                  <div className="flex h-72 items-center justify-center text-sm text-surface-500">
                    <RefreshCw size={16} className="mr-2 animate-spin" />
                    Loading folders...
                  </div>
                ) : pathBrowser.data && pathBrowser.data.entries.length > 0 ? (
                  <div className="divide-y divide-surface-100">
                    {pathBrowser.data.entries.map(entry => {
                      const isSelected = selectedPath === entry.path;
                      const canSelect = pathBrowser.mode === 'folder'
                        ? entry.type === 'directory'
                        : entry.type === 'file';

                      return (
                        <div
                          key={entry.path}
                          className={`flex items-center gap-3 px-3 py-2.5 text-sm ${
                            isSelected ? 'bg-primary-50' : 'bg-white hover:bg-surface-50'
                          }`}
                        >
                          <button
                            type="button"
                            onClick={() => {
                              if (canSelect) {
                                setPathBrowser(prev => prev ? { ...prev, selectedPath: entry.path } : prev);
                              }
                            }}
                            className="flex min-w-0 flex-1 items-center gap-3 text-left"
                          >
                            {entry.type === 'directory' ? (
                              <Folder size={17} className="shrink-0 text-amber-500" />
                            ) : (
                              <File size={17} className="shrink-0 text-surface-400" />
                            )}
                            <span className="truncate text-surface-800">{entry.name}</span>
                          </button>
                          {isSelected && <Check size={15} className="text-primary-600" />}
                          {entry.type === 'directory' && (
                            <Button
                              type="button"
                              size="sm"
                              variant="ghost"
                              onClick={() => browseToPath(entry.path)}
                            >
                              Open
                            </Button>
                          )}
                        </div>
                      );
                    })}
                  </div>
                ) : (
                  <div className="flex h-72 items-center justify-center text-sm text-surface-500">
                    No selectable items in this folder.
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="flex items-center justify-end gap-2 border-t border-surface-200 p-4">
            <Button type="button" variant="secondary" onClick={() => setPathBrowser(null)}>
              Cancel
            </Button>
            <Button type="button" onClick={applyBrowsedPath} disabled={!selectedPath}>
              Use Selected Path
            </Button>
          </div>
        </div>
      </div>
    );
  };

  if (showAddForm) {
    return (
      <AddServerSetup
        onCancel={() => setShowAddForm(false)}
        onSaved={() => {
          setShowAddForm(false);
          loadServers();
          api.loadActiveServer();
          onServerChange?.();
        }}
      />
    );
  }

  const activeServer = servers.find(server => server.id === activeId) || null;
  const activeEnvGroup = ENV_GROUPS.find(group => group.id === activeEnvGroupId) || ENV_GROUPS[0];
  const configuredFieldCount = ENV_GROUPS.flatMap(group => group.fields)
    .filter(field => String(envValues[field.key] ?? '').trim()).length;
  const totalFieldCount = ENV_GROUPS.reduce((total, group) => total + group.fields.length, 0);
  const configuredCountForGroup = (group: EnvGroup) => group.fields
    .filter(field => String(envValues[field.key] ?? '').trim()).length;
  const discordRequiredCount = DISCORD_REQUIRED_KEYS
    .filter(key => key === 'DISCORD_ENABLED' ? isToggleOn(envValues[key]) : String(envValues[key] ?? '').trim())
    .length;

  return (
    <div className="space-y-5">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <div className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-surface-900 text-white">
              <SlidersHorizontal size={22} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-surface-900">Settings</h2>
              <p className="text-sm text-surface-500">Manage servers, runtime configuration, paths, map settings, and the bundled @SST mod.</p>
            </div>
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          <Button size="sm" variant="secondary" onClick={loadRuntimeConfig} loading={configLoading}>
            <RefreshCw size={14} className="mr-1" />
            Reload
          </Button>
          <Button size="sm" variant="secondary" onClick={autoFillRuntimeConfig} disabled={!activeId || configLoading}>
            <Check size={14} className="mr-1" />
            Auto-fill blanks
          </Button>
          <Button size="sm" onClick={saveRuntimeConfig} loading={configSaving} disabled={!activeId || configLoading}>
            <Save size={14} className="mr-1" />
            Save .env
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-5 xl:grid-cols-[290px_minmax(0,1fr)]">
        <aside className="space-y-3">
          <Card compact className="xl:sticky xl:top-4">
            <div className="mb-3">
              <div className="text-sm font-semibold text-surface-900">Navigation</div>
              <div className="text-xs text-surface-500">{configuredFieldCount}/{totalFieldCount} settings filled</div>
            </div>

            <div className="space-y-1">
              {[
                { id: 'servers', title: 'Servers', description: `${servers.length} configured`, icon: <Server size={16} /> },
                { id: 'mod', title: 'SST Mod', description: modInfo?.exists ? 'Bundled mod ready' : 'Mod status', icon: <Package size={16} /> },
                ...ENV_GROUPS.map(group => ({
                  id: group.id,
                  title: group.title,
                  description: group.id === 'discord-support'
                    ? `${discordRequiredCount}/${DISCORD_REQUIRED_KEYS.length} required`
                    : `${configuredCountForGroup(group)}/${group.fields.length} filled`,
                  icon: group.icon,
                })),
              ].map(item => (
                <button
                  key={item.id}
                  type="button"
                  onClick={() => setActiveEnvGroupId(item.id)}
                  className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors ${
                    activeEnvGroupId === item.id
                      ? 'bg-surface-900 text-white'
                      : 'text-surface-700 hover:bg-surface-100'
                  }`}
                >
                  <span className={activeEnvGroupId === item.id ? 'text-white' : 'text-surface-500'}>
                    {item.icon}
                  </span>
                  <span className="min-w-0 flex-1">
                    <span className="block truncate text-sm font-medium">{item.title}</span>
                    <span className={`block truncate text-xs ${activeEnvGroupId === item.id ? 'text-surface-200' : 'text-surface-400'}`}>
                      {item.description}
                    </span>
                  </span>
                  <ChevronRight size={15} className="shrink-0 opacity-70" />
                </button>
              ))}
            </div>
          </Card>
        </aside>

        <main className="min-w-0 space-y-4">
          {configError && (
            <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">
              {configError}
            </div>
          )}

          {configMessage && (
            <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">
              {configMessage}
            </div>
          )}

          {activeEnvGroupId === 'servers' && (
            <Card compact>
              <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <h3 className="text-lg font-semibold text-surface-900">Server Connections</h3>
                  <p className="text-sm text-surface-500">One SST API profile per DayZ server.</p>
                </div>
                <Button onClick={() => setShowAddForm(true)} size="sm" icon={<Plus size={16} />}>
                  Add Server
                </Button>
              </div>

              {servers.length > 0 ? (
                <div className="grid grid-cols-1 gap-3 2xl:grid-cols-2">
                  {servers.map((server) => (
                    <div
                      key={server.id}
                      className={`rounded-xl border p-4 transition-colors ${
                        activeId === server.id
                          ? 'border-primary-300 bg-primary-50'
                          : 'border-surface-200 bg-white hover:border-surface-300'
                      }`}
                    >
                      {editingId === server.id ? (
                        <div className="space-y-3">
                          <input type="text" value={formName} onChange={(e) => setFormName(e.target.value)} placeholder="Server Name" className="w-full rounded-lg border border-surface-300 px-3 py-2 text-sm outline-none focus:border-primary-500" />
                          <input type="text" value={formUrl} onChange={(e) => setFormUrl(e.target.value)} placeholder="API URL" className="w-full rounded-lg border border-surface-300 px-3 py-2 text-sm outline-none focus:border-primary-500" />
                          <input type="text" value={formProfile} onChange={(e) => setFormProfile(e.target.value)} placeholder="API Profile (optional)" className="w-full rounded-lg border border-surface-300 px-3 py-2 text-sm outline-none focus:border-primary-500" />
                          <input type="password" value={formKey} onChange={(e) => setFormKey(e.target.value)} placeholder="API Key" className="w-full rounded-lg border border-surface-300 px-3 py-2 text-sm outline-none focus:border-primary-500" />
                          {formError && <p className="text-sm text-red-500">{formError}</p>}
                          <div className="flex gap-2">
                            <Button size="sm" onClick={() => handleUpdateServer(server.id)} icon={<Check size={14} />}>Save</Button>
                            <Button size="sm" variant="secondary" onClick={cancelEditing} icon={<X size={14} />}>Cancel</Button>
                          </div>
                        </div>
                      ) : (
                        <>
                          <div className="mb-3 flex items-start justify-between gap-3">
                            <div className="min-w-0">
                              <div className="flex flex-wrap items-center gap-2">
                                <h4 className="truncate font-semibold text-surface-900">{server.name}</h4>
                                {activeId === server.id && <Badge variant="success">Active</Badge>}
                                {testResults[server.id] === 'success' && <Badge variant="success">Connected</Badge>}
                                {testResults[server.id] === 'error' && <Badge variant="error">Failed</Badge>}
                              </div>
                              <div className="mt-2 space-y-1 text-xs text-surface-500">
                                <div className="flex min-w-0 items-center gap-2"><Globe size={12} /><code className="truncate">{server.apiUrl}</code></div>
                                <div className="flex items-center gap-2"><Key size={12} /><code>••••••••{server.apiKey.slice(-4)}</code></div>
                                <div className="flex items-center gap-2"><SlidersHorizontal size={12} /><code>{server.apiProfile || 'default API profile'}</code></div>
                                {server.mapPreset && <div className="flex items-center gap-2"><MapIcon size={12} /><span>{server.mapLabel || getMapPresetDefaults(server.mapPreset).label}</span></div>}
                                {server.lastUsed && <div className="flex items-center gap-2"><Clock size={12} /><span>Last used: {new Date(server.lastUsed).toLocaleDateString()}</span></div>}
                              </div>
                            </div>
                            <div className="flex shrink-0 gap-1">
                              <button onClick={() => startEditing(server)} className="rounded p-1.5 text-surface-500 hover:bg-surface-100 hover:text-surface-800" title="Edit">
                                <Edit2 size={14} />
                              </button>
                              <button onClick={() => handleDeleteServer(server.id)} className="rounded p-1.5 text-surface-500 hover:bg-red-50 hover:text-red-500" title="Delete">
                                <Trash2 size={14} />
                              </button>
                            </div>
                          </div>

                          <div className="flex flex-wrap gap-2">
                            {activeId !== server.id && <Button size="sm" onClick={() => handleSwitchServer(server.id)}>Switch</Button>}
                            <Button size="sm" variant="secondary" onClick={() => testConnection(server)} disabled={testingId === server.id} icon={<ExternalLink size={14} />}>
                              {testingId === server.id ? 'Testing...' : 'Test'}
                            </Button>
                          </div>
                        </>
                      )}
                    </div>
                  ))}
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-surface-200 py-14 text-center text-surface-500">
                  <Server size={42} className="mb-3 opacity-50" />
                  <p>No servers configured</p>
                  <p className="mt-1 text-sm">Add a server to get started.</p>
                </div>
              )}
            </Card>
          )}

          {activeEnvGroupId === 'mod' && (
            <Card compact>
              <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                <div>
                  <h3 className="text-lg font-semibold text-surface-900">SST Server Mod</h3>
                  <p className="text-sm text-surface-500">Copy the bundled @SST folder into a DayZ server folder.</p>
                </div>
                {modInfo && <Badge variant={modInfo.exists ? 'success' : 'error'}>{modInfo.exists ? 'Bundled' : 'Missing'}</Badge>}
              </div>

              {modInfo ? (
                <div className="space-y-4">
                  <div className="rounded-xl border border-surface-200 bg-surface-50 p-4">
                    <div className="mb-2 text-xs font-semibold uppercase tracking-wide text-surface-500">Bundled Path</div>
                    <code className="block break-all rounded-lg bg-white px-3 py-2 text-xs text-surface-700 ring-1 ring-surface-200">{modInfo.path}</code>
                    <div className="mt-3 flex flex-wrap gap-2">
                      <Button size="sm" variant="secondary" onClick={copyModPath} disabled={!modInfo.exists} icon={<Copy size={14} />}>Copy Path</Button>
                    </div>
                  </div>

                  <div className="rounded-xl border border-surface-200 bg-white p-4">
                    <div className="mb-3">
                      <div className="text-sm font-semibold text-surface-800">Install Destination</div>
                      <p className="text-xs text-surface-500">Choose the DayZ server root. SST will copy into an @SST folder there.</p>
                    </div>
                    <div className="grid gap-2 lg:grid-cols-[1fr_auto_auto]">
                      <input
                        value={modDestination}
                        onChange={(event) => {
                          setModDestination(event.target.value);
                          setModError('');
                          setModMessage('');
                        }}
                        placeholder="DayZ server folder, e.g. D:\\DayZServer"
                        className="w-full rounded-lg border border-surface-300 px-3 py-2 text-sm outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-100"
                      />
                      <Button
                        type="button"
                        size="sm"
                        variant="secondary"
                        onClick={() => openPathBrowserTarget('__modDestination', 'DayZ server folder', 'folder', modDestination)}
                        icon={<FolderOpen size={14} />}
                      >
                        Browse
                      </Button>
                      <Button size="sm" onClick={copyModToDestination} loading={modCopying} disabled={!modInfo.exists} icon={<FolderOpen size={14} />}>
                        Copy @SST
                      </Button>
                    </div>
                    {modMessage && <div className="mt-2 text-xs text-emerald-700">{modMessage}</div>}
                    {modError && <div className="mt-2 text-xs text-red-700">{modError}</div>}
                  </div>
                </div>
              ) : (
                <div className="text-sm text-surface-500">Mod information is not loaded yet.</div>
              )}
            </Card>
          )}

          {activeEnvGroupId !== 'servers' && activeEnvGroupId !== 'mod' && (
            <Card compact>
              <div className="mb-4 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                <div className="min-w-0">
                  <div className="flex items-center gap-2 text-surface-500">
                    {activeEnvGroup.icon}
                    <span className="text-xs font-semibold uppercase tracking-wide">Active Server .env</span>
                  </div>
                  <h3 className="mt-1 text-lg font-semibold text-surface-900">{activeEnvGroup.title}</h3>
                  <p className="mt-1 text-sm text-surface-500">{activeEnvGroup.description}</p>
                </div>
                <div className="rounded-xl border border-surface-200 bg-surface-50 px-3 py-2 text-xs text-surface-500">
                  <div><span className="font-medium text-surface-700">Server:</span> {activeServer?.name || 'None selected'}</div>
                  {envPath && <div className="mt-1 break-all"><span className="font-medium text-surface-700">.env:</span> {envPath}</div>}
                </div>
              </div>

              {!activeId ? (
                <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-surface-200 py-14 text-center text-surface-500">
                  <Server size={40} className="mb-3 opacity-50" />
                  <p>Select or add a server before editing runtime settings.</p>
                </div>
              ) : activeEnvGroup.id === 'discord-support' ? (
                renderDiscordSupportPanel()
              ) : (
                <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
                  {activeEnvGroup.fields.map(renderEnvField)}
                  {activeEnvGroup.id === 'mission-expansion' && renderExpansionAutoPaths()}
                </div>
              )}
            </Card>
          )}
        </main>
      </div>

      {renderPathBrowserModal()}
    </div>
  );
};

export default ServerSettings;
